# # Generated by Django 4.1.13 on 2024-11-11 08:32

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('shift_api', '0002_user_delete_customuser'),
#     ]

#     operations = [
#         migrations.CreateModel(
#             name='Product',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('name', models.CharField(max_length=100)),
#                 ('price', models.DecimalField(decimal_places=2, max_digits=10)),
#                 ('description', models.TextField()),
#             ],
#         ),
#         migrations.DeleteModel(
#             name='User',
#         ),
#     ]

from django.db import migrations
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType

def create_permissions(apps, schema_editor):
    Users = apps.get_model('app_name', 'Users')  # استبدل app_name باسم تطبيقك
    content_type = ContentType.objects.get_for_model(Users)
    Permission.objects.create(
        codename='can_delete_user',
        name='Can Delete User',
        content_type=content_type,
    )

class Migration(migrations.Migration):

    dependencies = [
        # أضف أي تبعيات هنا إذا لزم الأمر
    ]

    operations = [
        migrations.RunPython(create_permissions),
    ]
