# Generated by Django 5.1.3 on 2024-11-18 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift_api', '0003_product_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
